### ISSUE TITLE
dotnet new doesn't work

### ISSUE THREAD

**Issue by rastreus** [petabridge/petabridge-dotnet-new#146]
Related: #127 
Related: #136 
Related: #141 

I do not think that the v1.0.2 release fixed this issue.

I attempted to install the Templates with `dotnet new -i "Petabridge.Templates::*"` and then uninstalled and reinstalled with `dotnet new --install Petabridge.Templates::1.0.2` after the first install didn't work.

Both install attempts showed that only the pb-akka-cluster template was installed. But when I attempted to use the cluster template, the console responded with `Couldn't find an installed template that matches the input, searching online for one that does...`

**Comment by Aaronontheweb** [comment]
@rastreus I think you're right - @dependabot sent in a bunch of PRs again with subsequent updates (don't know why we missed them the first time.)

**Comment by gjreige** [comment]
Unfortunately I believe the same issue appears (at least for me) in version 1.0.3.

![image](https://user-images.githubusercontent.com/2173306/69657008-de024780-1079-11ea-8cb8-a7e016e1a624.png)

I tried to install the Petabridge.App template manually and it works (template is created) except when I run it I get this error:

![image](https://user-images.githubusercontent.com/2173306/69657515-a47e0c00-107a-11ea-9476-dde7f9548fae.png)

Dont know if this helps.

**Comment by rastreus** [comment]
@gjreige This is also what happened for me when I tried using version 1.0.3.

**Comment by Aaronontheweb** [comment]
Sigh....

**Comment by Aaronontheweb** [comment]
Give this a try: https://github.com/petabridge/petabridge-dotnet-new/releases/tag/1.0.4 - I think I overwrote the submodule PRs by accident last time.

**Comment by rastreus** [comment]
@Aaronontheweb Version 1.0.4 has fixed the issues that I was seeing. I was able to successfully install and use all three of the templates.

<img width="1242" alt="petabridge-templates-installed" src="https://user-images.githubusercontent.com/1581009/69665705-c908c280-103f-11ea-8b5a-ffbe7b958794.png">
<img width="1242" alt="petabridge-templates-successful" src="https://user-images.githubusercontent.com/1581009/69665719-ce660d00-103f-11ea-9250-ffc9153c9c27.png">

Thank you for getting this fixed, Aaron. I'm closing the issue at this time.

Related: #156
