### ISSUE TITLE
chmod +x build.sh

### ISSUE THREAD

**Issue by ayoung** [petabridge/petabridge-dotnet-new#6]
After running pb-lib build.sh was not automatically executable. Had to run `chmod +x build.sh` first. Can you make this automatic or somehow check in the file mode into the repo?

**Comment by Aaronontheweb** [comment]
@ayoung mind sending a pull request? :D

**Comment by ayoung** [comment]
Yep. I kind of did that so I don't forget about it. I'll circle around to
making the PR when I get some spare cycles.
